/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LATIHAN;

import javax.swing.JOptionPane;

/**
 *
 * @author Nita
 */
public class Latihan3Lanjutan extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3Lanjutan
     */
    public Latihan3Lanjutan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tbalok = new javax.swing.JTextField();
        pbalok = new javax.swing.JTextField();
        lbalok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pkubus = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        volume = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pbola = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        vbola = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Masukkan Tinggi   :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 110, 130, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cm");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 120, 30, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Masukkan Lebar    :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 70, 130, 20);
        jPanel1.add(tbalok);
        tbalok.setBounds(160, 110, 90, 30);
        jPanel1.add(pbalok);
        pbalok.setBounds(160, 30, 90, 30);
        jPanel1.add(lbalok);
        lbalok.setBounds(160, 70, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Masukkan Panjang :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 30, 130, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 40, 30, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 80, 30, 20);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        jPanel1.add(hitung);
        hitung.setBounds(140, 180, 90, 30);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Cm");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(190, 60, 21, 20);
        jPanel2.add(pkubus);
        pkubus.setBounds(30, 60, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Masukkan Panjang sisi ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 30, 138, 20);

        volume.setText("Volume");
        volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeActionPerformed(evt);
            }
        });
        jPanel2.add(volume);
        volume.setBounds(20, 110, 80, 30);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cm");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(150, 60, 21, 20);

        pbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbolaActionPerformed(evt);
            }
        });
        jPanel3.add(pbola);
        pbola.setBounds(30, 60, 100, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari-Jari ");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 30, 167, 20);

        vbola.setText("Volume");
        vbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vbolaActionPerformed(evt);
            }
        });
        jPanel3.add(vbola);
        vbola.setBounds(50, 110, 67, 23);

        jTabbedPane1.addTab("Bola", jPanel3);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Program Pencarian Bangunan Ruang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel11)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        int panjang,lebar,tinggi;
        panjang = Integer.parseInt(pbalok.getText());
        lebar = Integer.parseInt(lbalok.getText());
        tinggi = Integer.parseInt(tbalok.getText());
        
        int hasil = panjang*lebar*tinggi;
        try {
            JOptionPane.showMessageDialog(null, "Volume Balok adalah :"+hasil,"luas", 
                    JOptionPane.INFORMATION_MESSAGE);           
        }catch (Exception e) {
           JOptionPane.showMessageDialog(null,"Error : "+e,"Gagal",JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void volumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(pkubus.getText());
        int hasil= sisi*sisi*sisi;
        
        try {
            JOptionPane.showMessageDialog(null,"Luas Permukaan Kubus adalah :"+hasil,"luas", 
                    JOptionPane.INFORMATION_MESSAGE); 
        }catch (Exception e) {
           JOptionPane.showMessageDialog(null,"Error : "+e,"Gagal",JOptionPane.WARNING_MESSAGE); 

        }
    }//GEN-LAST:event_volumeActionPerformed

    private void vbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vbolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari = Integer.parseInt(pbola.getText());
        float hasil1 = (float)(4/3*3.14*jari*jari*jari);
        
        try {
            JOptionPane.showMessageDialog(null,"Luas Permukaan Bola adalah :"+hasil1,"luas", 
                    JOptionPane.INFORMATION_MESSAGE); 
        }catch (Exception e) {
           JOptionPane.showMessageDialog(null,"Error : "+e,"Gagal",JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_vbolaActionPerformed

    private void pbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pbolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3Lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3Lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3Lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3Lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3Lanjutan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lbalok;
    private javax.swing.JTextField pbalok;
    private javax.swing.JTextField pbola;
    private javax.swing.JTextField pkubus;
    private javax.swing.JTextField tbalok;
    private javax.swing.JButton vbola;
    private javax.swing.JButton volume;
    // End of variables declaration//GEN-END:variables
}
